#!/bin/bash
# Retint rofi — and everything launched through it, e.g. clipmenu.
#
#   rofi_theme.sh   — read ~/.local/state/theme, write rofi's colour include
#
# The adi1090x theme in ~/.config/rofi keeps its palette in shared/colors.rasi
# and uses each colour twice: as a surface AND as the text drawn on it
# (`selected-normal-foreground: var(background)`), the same trick the dwm bar
# and tmux status line use. Values therefore follow those palettes:
#
#   key              role                        dark        light
#   background       surface                     #011627     #FAFAFA
#   background-alt   alternating rows / chips    #0b2942     #E6E9EF
#   foreground       normal text                 #d6deeb     #000000
#   selected         selection surface           #82aaff     #1E66F5
#   active           active surface              #c792ea     #8839EF
#   urgent           urgent surface              #ef5350     #D20F39
#
# RoFI's own config lives outside this repo, so the original colors.rasi is
# kept as colors.rasi.dotfiles-bak on first run. A config.rasi is created if
# missing: invocations that pass no -theme (clipmenu does not) would otherwise
# fall back to rofi's built-in defaults.
#
# Prints "applied <theme>"; exits 0 when rofi is not configured on this host.

set -u

STATE_FILE="${XDG_STATE_HOME:-$HOME/.local/state}/theme"
ROFI_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/rofi"
COLORS="$ROFI_DIR/shared/colors.rasi"
CONFIG="$ROFI_DIR/config.rasi"
THEME="$(cat "$STATE_FILE" 2>/dev/null || echo dark)"

[ -d "$ROFI_DIR" ] || { echo "skipped: $ROFI_DIR missing"; exit 0; }

if [ "$THEME" = "light" ]; then
    bg="#FAFAFAFF"; bg_alt="#E6E9EFFF"; fg="#000000FF"
    sel="#1E66F5FF"; act="#8839EFFF"; urg="#D20F39FF"
else
    bg="#011627FF"; bg_alt="#0b2942FF"; fg="#d6deebFF"
    sel="#82aaffFF"; act="#c792eaFF"; urg="#ef5350FF"
fi

mkdir -p "$ROFI_DIR/shared"
[ -f "$COLORS" ] && [ ! -f "$COLORS.dotfiles-bak" ] && cp -p "$COLORS" "$COLORS.dotfiles-bak"

cat >"$COLORS.tmp" <<EOF
/**
 * GENERATED by dotfiles configs/theme/scripts/rofi_theme.sh — do not edit.
 * theme: $THEME (from $STATE_FILE)
 **/

* {
    background:     $bg;
    background-alt: $bg_alt;
    foreground:     $fg;
    selected:       $sel;
    active:         $act;
    urgent:         $urg;
}
EOF
mv "$COLORS.tmp" "$COLORS"

if [ ! -f "$CONFIG" ]; then
    printf '@theme "current.rasi"\n' >"$CONFIG"
    echo "applied $THEME (created config.rasi)"
else
    echo "applied $THEME"
fi
