#                                 

# Configurations

# Format

format = """
$username$directory$git_branch$git_status$fill
 $character
"""

right_format = """$all$time"""


# General config

[username]
style_user = "fg:#0969da"
style_root = "fg:#45aeff"
format = '[\[$user\]]($style)'
disabled = true 

#  ❯ ❮ ✘
[character]
success_symbol = '[](bold green)'
error_symbol = '[](bold red)'
vimcmd_symbol = '[](bold green)'
vimcmd_replace_one_symbol = '[ ](bold purple)'
vimcmd_visual_symbol = '[ ](bold green)'

[directory]
truncation_length = 8 
truncate_to_repo = false
before_repo_root_style="fg:#0969da"
repo_root_style="fg:#89c0d0"
style="fg:#45aeff"
read_only=" "
read_only_style="red"
repo_root_format ='\[[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style)\]'
format='\[[$path]($style)[$read_only]($read_only_style)\]'
disabled = false

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[fill]
symbol = "·"
style = "fg:#e4e4e4"

[git_branch]
symbol = ""
style = "fg:#f0268f"
format = '[\[$symbol $branch\]]($style)'
disabled = false

[git_status]
style = "fg:#65ff87"
ahead ='󰞕 $count'
behind ='󰞒 $count'
modified = '!$count'
untracked = '?$count'
stashed = '\$$count'
staged = '+$count'
deleted = '✘$count'
conflicted = '=$count'
format = '([\[$all_status$ahead_behind\]]($style))'
disabled = false

[time]
disabled = false
time_format = "%T" # Hour:Minute Format
style = "fg:#65ff87"
format = '([\[$time\]]($style))'

[cmd_duration]
style = "fg:#f1d751"
format = '([\[$duration\]]($style))'

# Start languages and tools #

[nix_shell]
symbol = " "
style = "fg:#90b7e0"
format = '([\[$symbol ($version)\]]($style))'
disabled = false

[docker_context]
symbol = "󰡨 "
style = "fg:#589be9"
format = '(via [\[$symbol $context\]]($style))'
disabled = false

[bun]
symbol = "󱠶 "
style = "fg:#da9253"
version_format = "$raw"
format = '(via [\[$symbol $context\]]($style))'
disabled = false

[c]
symbol = ""
style = "fg:#84a930"
version_format = "$raw"
format = '([\[$symbol ($version)\]]($style))'
disabled = false

[kubernetes]
style = "fg:#326ce5"
format = '([\[on ﴱ ($user on )($cluster in )$context \($namespace\)\]]($style))'
disabled = false

[gcloud]
symbol = " "
style = "fg:#0f9d58"
format = '([ \[on $symbol $account(@$domain)(\($region\))\]]($style) )'
# format = '[ on $symbol account@company.iam.gserviceaccount.com(\($region\)) ]($style) ' # for testing purposes
disabled = false

[golang]
symbol = ""
style = "fg:#007d9c"
version_format = "$raw"
format = '([\[$symbol ($version)\]]($style))'
disabled = false

[java]
symbol = ""
style = "fg:#cd6f1a"
version_format = "$raw"
format = '([\[$symbol ($version)\]]($style))'
disabled = false

[lua]
symbol = ""
style = "fg:#5582da"
version_format = "$raw"
format = '([\[$symbol ($version)\]]($style))'
disabled = false

[nodejs]
symbol = ""
style = "fg:#5fa04e"
version_format = "$raw"
format = '([\[$symbol ($version)\]]($style))'
disabled = false

[package]
symbol = " "
style = "fg:#cb3837"
version_format = "$raw"
format = '([\[$symbol ($version)\]]($style))'
disabled = false

[php]
symbol = ''
style = "fg:#4F5B93"
version_format = "$raw"
format = '([\[$symbol ($version)\]]($style))'
disabled = false

[python]
symbol = ''
version_format = "$raw"
pyenv_version_name = true
style = "fg:#ffdf76"
format = '([\[$symbol ($version)\]]($style))'
disabled = false

[rust]
symbol = ""
style = "fg:#9e6a4b"
version_format = "$raw"
format = '([\[$symbol ($version)\]]($style))'
disabled = false

[scala]
symbol = ""
style = "fg:#a72145"
version_format = "$raw"
format = '([\[$symbol ($version)\]]($style))'
disabled = false

# End languages and tools #

# OS SYMBOLS
[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

