lastupdatecheck: 0
recentrepos:
- /home/eduardoneville/Desktop/UNI/BA6/Swent/Knight
- /home/eduardoneville/Desktop/AiRs/LLM-Testing-Hcktn/enwik9-compression
- /home/eduardoneville/dotfiles
- /home/eduardoneville/Desktop/AiRs/MeteoData
- /home/eduardoneville/Desktop/AiRs/Malware_Agent
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: false
