lastupdatecheck: 0
recentrepos:
- /home/eduardoneville/Desktop/AiRs/MeteoData
- /home/eduardoneville/Desktop/UNI/BA6/SemProj/ec-llm
- /home/eduardoneville/dotfiles
- /home/eduardoneville/Desktop/AiRs/Malware_Agent
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: false
