lastupdatecheck: 0
recentrepos:
- /home/eduardoneville/Desktop/AiRs/Malware_Agent
- /home/eduardoneville/Desktop/UNI/OS/lab-4-EduardoNeville
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: false
