lastupdatecheck: 0
recentrepos:
- /home/eduardoneville/Desktop/AiProjs/Multifaceted-Benchmarking/benchmarks/thoery_of_mind_gpt4
- /home/eduardoneville/Desktop/AiProjs/Multifaceted-Benchmarking
- /home/eduardoneville/Desktop/AiProjs/Multifaceted-Benchmarking/benchmarks/machiavelli
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: false
ignorewhitespaceindiffview: false
